global:
  app:
    version: "1.0"
    name: LiveInvesting
    namespace: prod-lt
    imagePullSecrets: docker-secret
deployment:
  # trade position service
  tradepositionservice:
    image: organisation/onboarding_tradeposition_service_lt
    tag: prod
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Prod"
    ports:
    - containerPort: 9000
    replicacount: 1
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 80
      memoryUtilization: 80
    resources:
      limits:
        cpu: 800m
        memory: 900Mi
      requests:
        cpu: 500m
        memory: 756Mi
    readinessProbe:
      httpGet:
        path: /health/ok
        port: 9000
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 24
      successThreshold: 1
    livenessProbe:
      httpGet:
        path: /health/ok
        port: 9000
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 1
    command:
      commandDefinations:
        command: [ "java", "-jar", "/opt/app/*.jar" ]

  # transactions funds monitor service
  transactionsfunds-monitori-service:
    image: organisation/transactionfund.fundsstatusmonitor_lt
    tag: prod
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Prod"
    ports:
    - containerPort: 8081
    replicacount: 1
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 80
      memoryUtilization: 80
    resources:
      limits:
        cpu: 800m
        memory: 900Mi
      requests:
        cpu: 500m
        memory: 756Mi
    readinessProbe:
      httpGet:
        path: /health/ok
        port: 8081
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 24
      successThreshold: 1
    livenessProbe:
      httpGet:
        path: /health/ok
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 1
    command:
      commandDefinations:
        command: [ "dotnet", "Transaction.FundsStatusMonitor.dll" ]

  # transactions-new-deployment
  transactions-new-service:
    image: organisation/onboarding_new_transactions_lt
    tag: prod
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Prod"
    ports:
    - containerPort: 80
    replicacount: 1
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      cpuUtilization: 80
      memoryUtilization: 80
    resources:
      limits:
        cpu: 800m
        memory: 900Mi
      requests:
        cpu: 500m
        memory: 756Mi
    readinessProbe:
      httpGet:
        path: /health/ok
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 24
      successThreshold: 1
    livenessProbe:
      httpGet:
        path: /health/ok
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 1
    command:
      commandDefinations:
        command: [ "dotnet", "Transaction.WebApi.dll" ]

################# Services #############################

services:
  # tradepositionservice
  tradepositionservice:
    name: tradepositionservice
    externalTrafficPolicy: Cluster
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
    selector:
      app: tradepositionservice

  # transactions-new-service
  transactions-new-service:
    name: transactions-new-service
    ports:
    - port: 7252
      targetPort: 80
      protocol: TCP
    selector:
      run: transactions-new-service
